version: ENC[AES256_GCM,data:27RB,iv:P9nn4vCF+zOPUFfLyrslAivCsRDgk4YLboT0hI/u/Lo=,tag:D+QS8DW+y5elMhulQD5EAw==,type:str]
services:
    db:
        image: ENC[AES256_GCM,data:Cxb2v7xZASD6N1nM,iv:F1cgIqo2kX/GHwaWimSj7h2GDhbCaw+BaVhaQY9w2B4=,tag:6lsYTyqFuMDfeKanqjmReg==,type:str]
        volumes:
        - ENC[AES256_GCM,data:m9BRFrpVWi/ED1yxVr7IwR6AI87vRw==,iv:CbK8R8mmSN0aqQ2notYnuGe7ROvxEGaIJHkXNPp13ic=,tag:zpEEpXf9kGSn3s7QMTdz1Q==,type:str]
        environment:
            MYSQL_ROOT_PASSWORD_FILE: ENC[AES256_GCM,data:HOVfOxSJWnC0XFccRFCJfS2d+BbjOuG8XYoQHJM=,iv:dnQpwJxntGNHP1r01DfctrUIw+FZteVs5tJWOhe+T/s=,tag:Vr5gpCkVb4pcuCb8J64Njw==,type:str]
            MYSQL_DATABASE: ENC[AES256_GCM,data:fgPPrAPaVeDW,iv:inA4cSQaFF3AyC9LjeXu0MVNBS5mZRkh7BOUtWQ0fvk=,tag:pYYcX42IaI0WeGNdYqSI0Q==,type:str]
            MYSQL_USER: ENC[AES256_GCM,data:w1uJf7CF3wm4,iv:xtenzwRf/H+WezGIqmUcW3eCV0Ll7Ghz4WSJw1szUpY=,tag:w0tFxW/MZZqle0s04RrhYA==,type:str]
            MYSQL_PASSWORD_FILE: ENC[AES256_GCM,data:dpA9uW0IiKD9PzmpO890c7hffdlnAO13,iv:YI6jBG/EMEyRGycmVGPI7YNjjLJXhjLBN0/U6y6SXWc=,tag:tIUguyQfG12qMa/i3EOisg==,type:str]
        secrets:
        - ENC[AES256_GCM,data:bN9oekTQX+6Y2GQh8MLJjg==,iv:5lPaohndM/tRbdvI/iKK38v1Wd1njPcU4b62FmFVDa0=,tag:DAVOWXlSlxZchzCbL+Qo4A==,type:str]
        - ENC[AES256_GCM,data:RMw96LLLmN6adWg=,iv:q8zhzhyblCMGR0uG7yF6MdTsWgSSN8xCSW/nMe7EPWs=,tag:k8kWUruBUTx1UnzMFGbWoA==,type:str]
    wordpress:
        depends_on:
        - ENC[AES256_GCM,data:NEQ=,iv:Ppsfg4VkGgm0cDnzmortRNLBBw/i4MSRDJoUQgIoOz8=,tag:x5WMT+0LesNvd/B7JqrMrQ==,type:str]
        image: ENC[AES256_GCM,data:NBT2/jFxpOy7/Blv97t+Kw==,iv:w/MvfArNSeQSJduabHwK8IUeXDuvsxgJ2N1M4I9fFrk=,tag:VRoVhzxFFUmC+c4/vJ2L1A==,type:str]
        ports:
        - ENC[AES256_GCM,data:dQOYRRa2ag==,iv:Mw2UQfU5xEN2KEG7Jarx5VBQTz2vtZBAEmG3FNuF+E8=,tag:BFeRA0k+To4JEGanfbmtIQ==,type:str]
        environment:
            WORDPRESS_DB_HOST: ENC[AES256_GCM,data:bxfPAFttWw==,iv:5gWglxjds/o4NhaUYDPQTTkanylOGM6eF0wt/03pNJg=,tag:s63DZoR8Z0cjjy23+wAqPg==,type:str]
            WORDPRESS_DB_USER: ENC[AES256_GCM,data:R1eTVM/EJkHL,iv:moWhpzEOtX3rK48Qt4N+Vl2oI9GenwHx72ifFGXKhPQ=,tag:xth6VdBGO+4qL+E3KvScIw==,type:str]
            WORDPRESS_DB_PASSWORD_FILE: ENC[AES256_GCM,data:57E3d5dtUTbYahj6FDiJC9IvYxTcekBf,iv:ObeLMNjCeWK1ZhTq73cT7lh+PBTDOrNHGOlHMBjjPdI=,tag:cQQI3Q7SGzgnrmL3jVHmKQ==,type:str]
        secrets:
        - ENC[AES256_GCM,data:ePOqe60yxWY1IJo=,iv:GKQmTCeIsD0eG0ZvGmJxcWO8yRJoeJ2oZwbBTgn+LD0=,tag:uzivA6lJ8nUtZjvo1GVDOw==,type:str]
secrets:
    db_password:
        file: ENC[AES256_GCM,data:fD0ETUzcFfAHM04mAB10,iv:xO+lwXf2QlHIqA/kkvRqhfYv77dMV1siaXBzeP9XZIs=,tag:mO2v343RJDPIVR/VEJHFzg==,type:str]
    db_root_password:
        file: ENC[AES256_GCM,data:QUKTgUSG8louxC3VTh6SYPGiRYs=,iv:/bZvbQpnWbSoKTd+5WTvqrglmvWSbCEmoqA1KJ/4NqQ=,tag:uFZxhi2XVjfGRAOboPDVWQ==,type:str]
volumes:
    db_data: null
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/sops-246117/locations/global/keyRings/git-secrets/cryptoKeys/master
        created_at: '2019-07-09T22:04:36Z'
        enc: CiQANNgcMIzjLR75DXCpWsUCyAL4XiJ7CGjt2ofcYRRvT+ac76QSSQDFeq+pUorGR1wZBAesQtMC5PD68Ps16yoH4KrEXbPWPsML1MiqYqdr1P8H6PLPy0cSwXK8+n9VlSeve3qyNATr38fZhDnG+Ec=
    azure_kv: []
    lastmodified: '2019-07-09T22:05:06Z'
    mac: ENC[AES256_GCM,data:nZbULe5DiY51DIW0wZvUT8zme8ItSTzx96TWAvyVs1OoYNcO7uxs1OTaMDfBmvYRPHhb/+9TdMBIfv/RB3ufWFKvH67kibl7Fn9vWUDDjhQAULP4JGhX5UJKWYbT1eIXQCisiLDQBda+RCz6saOQ7G+ho98OtMA9VDYTRuXiLa0=,iv:yyKO5GOLw42b99QueH2cSvqjedvb2f/xTjl4FAPS1ns=,tag:H44KHf5WWJgWsgCnNwqDHw==,type:str]
    pgp:
    -   created_at: '2019-07-09T22:04:36Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMAwdrjPMG5285AQf/dFQuryx50RCX2fNGZOtAMDVBU1iizSO0CaP/9a8gAPVF
            rg32ZvxvoQyCClZ/iclvv5uVnSiEHM7lDmzJEfPeAntAMbqE1Q2xNo4nuo/kmcEQ
            I4u/EIhJTUI8FMu4U33guavQDn1z+lANrM1C7RsMrFlCP+ny7ZPBnEt5Qgz8q6fB
            tkqIls5Dg0zjGnOpd+FEmZ8qtvqg7kGWUyJBOUuqpkVt25Z5sBCKCpOO7lTyA4yx
            6wauM1LQ3ZSM0ByYcpAYHmB5nwpNzXh6NAcADJXl2JbJ7H3g5krxOnEXlB1MnIbA
            S3iX087sthym3GF90ejsMaw/G/eNWZ0fk5kOsbWpNNJeAUskK+KCdNHxs0FJnm68
            UbKN4/So0pIiN8ESnZiLhAk/c54YssnAmLCKM+4sJWJgOzbKCkFzSjoGliqCzFW1
            q3N2u9OQ9TnIS6muuCp9XnXq93PvdHtaY3NAVkxHbA==
            =Jncm
            -----END PGP MESSAGE-----
        fp: F009D47AE9B844590BDA8BA5A39451B1377A25BD
    unencrypted_suffix: _unencrypted
    version: 3.3.1
